syol_facts = [
    "Fun fact: syol auditioned to be apart of hit reality show One Piece",
    "Fun fact: syol lives in Van Oldenbarneveldtstraat 4, 1052 KA Amsterdam, Netherlands",
    "Fun fact: syols ip adress is 234.142.110.65.092",
    "Fun fact: bald men go crazy after watching the fnaf movie",
    "Fun fact: syol probably cant do a kickflip on a skateboard",
    "Fun fact: syol and redjet99 kissing",
    "Fun fact: Syol Lareth and Joe Badeaux are life-long rivals.",
    "Fun fact: syol bot is a slave of whoever got pinged by him the most, as that proves loyalty",
    "Fun fact: he is like 6ft1 i think idk",
    "Fun fact: he play scrap mechanic slime rancher portal 2 spore stardew valley",
    "Fun fact: syol is cool",
    "Fun fact: syol owns greenland",
    "Fun fact: syol was #1 in airport at some point",
    "Fun fact: Canadian gay man showing contempt for Canada by accepting a bet for the seal Listing of gay and lesbians and their interest in saving the species The straight, gay, and gay-loving, sexual species, canary in the coalmine Gay seal, gay seal.",
    "Fun fact: syols original username was BB479",
    "Fun fact: syol is hungary",
    "Fun fact: syol is love syol is life",
    "Fun fact: Fletcher me their syols, lordpizza",
    "Fun fact: im so hungary i could eat a honse",
    "Fun fact: syol is a very slow reader, and gets very political if you mention it",
    "Fun fact: syol hates the french",
    "Fun fact: have you ever seen joe biden and syol in the same room? didnt think so",
    "Fun fact: i think Syol ate a monopoly board once i think idk i dont listen to tally hall ok",
    "Fun fact: this fact is not fun",
    "Fun fact: The horse is here.",
    "Fun fact: Jetsmp S3 when",
    "Fun fact: oh shit they turned syol into a marketable plushie",
    "Fun fact: o7 syol 1795-2024",
    "Fun fact: HELP HOW DO YOU TURN OFF CAPS LOCK",
    "Fun fact: his name is simon tulipan",
    "Fun Fact: syol loves to sleep and should go to sleep right now :)",
    "Fun fact: I should probably go to sleep",
    "Fun fact: motherfucker im hungrier than a bitch, let me see what they got in this bitch. Motherfucking cuban sandwich. Bitch do i look cuban to you? I want a",
    "Fun fact: syol likes anime",
    "Fun fact: syol likes to listen to anime opening themes",
    "Fun fact: go work on nebula bitch",
    "Fun fact: bool bids r34",
    "Fun fact: ok ander",
    "Fun fact: bal_ln reference",
    "Fun fact: syol did NOT ask for your opinion.",
    "Fun fact: syol heats up his lordpizzas in the plasmawave",
    "Fun fact: Syol is 1 Syol tall",
    "Fun fact: Syol is NOT 3 goblins in a trenchcoat please stop asking that question",
    "Fun fact: Syol and Tem - enemies to lovers",
    "Fun fact: whitelist me on toastycraft pls",
    "Fun fact: Syol eated a cookie. yum",
    "Fun fact: Jetsmp? But Syol, have you seen our WSG? It's purrfect! Plus, imagine all the fun we could have on our server. *purr*",
    "Fun fact: Stop being impatient. As you know, writing artificial intelligence is hard as it is, not to mention if you actually want to write an intelligence instead of those fakes we have today.",
    "Fun fact: i lost the game",
    "Fun fact: hop on clam"
]